use dwh;
-- Create the REGION table
CREATE TABLE region (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL);

-- Create the SALES_REP table
CREATE TABLE SALES_REP (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    REGION_ID INT REFERENCES REGION(ID)
);

-- Create the ACCOUNTS table
CREATE TABLE account (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    WEBSITE VARCHAR(255),
    LAT DECIMAL(9,6),
    longitude float(9,6),
    PRIMARY_POC VARCHAR(255),
    SALES_REP_ID INT REFERENCES SALES_REP(ID)
);

-- Create the WEB_EVENTS table
CREATE TABLE WEB_EVENTS (
    ID SERIAL PRIMARY KEY,
    ACCOUNT_ID INT REFERENCES ACCOUNTS(ID),
    OCCURRED_AT TIMESTAMP,
    CHANNEL VARCHAR(255)
);

-- Create the ORDERS table
CREATE TABLE ORDERS (
    ID SERIAL PRIMARY KEY,
    ACCOUNT_ID INT REFERENCES ACCOUNTS(ID),
    OCCURRED_AT TIMESTAMP,
    STANDARD_QTY INT,
    GLOSS_QTY INT,
    POSTER_QTY INT,
    TOTAL INT,
    STANDARD_AMOUNT_USD DECIMAL(10, 2),
    GLOSS_AMOUNT_USD DECIMAL(10, 2),
    POSTER_AMOUNT_USD DECIMAL(10, 2),
    TOTAL_AMOUNT_USD DECIMAL(10, 2)
);

select * from region;
select * from sales_rep;
select * from accounts;
select * from web_events;
select * from orders;

